FROM node:22.10.0 AS build

WORKDIR /app

COPY ./apps/zip/package.json ./apps/zip/package.json

COPY ./libs/zap/package.json ./libs/zap/package.json

COPY ./package-lock.json ./package-lock.json

COPY ./package.json ./package.json

RUN npm ci

COPY ./apps/zip/src ./apps/zip/src

COPY ./apps/zip/tsconfig.json ./apps/zip/tsconfig.json

COPY ./libs/zap/src ./libs/zap/src

COPY ./libs/zap/tsconfig.json ./libs/zap/tsconfig.json

COPY ./lerna.json ./lerna.json

RUN npm exec -- lerna run build:development --scope zap

RUN npm exec -- lerna run build:development --scope zip

FROM node:22.10.0 AS image

WORKDIR /app

COPY --from=build /app/apps/zip/dist /app/apps/zip/dist

COPY --from=build /app/apps/zip/package.json /app/apps/zip/package.json

COPY --from=build /app/libs/zap/dist /app/libs/zap/dist

COPY --from=build /app/libs/zap/package.json /app/libs/zap/package.json

COPY --from=build /app/node_modules /app/node_modules

COPY --from=build /app/lerna.json /app/lerna.json

COPY --from=build /app/package.json /app/package.json

CMD ["npm", "exec", "--", "lerna", "run", "start:production", "--scope", "zip"]