name: development

on:
  push:
    branches: development

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
  ls:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: ls
        run: ls ./